spring.application.name=matcher

spring.datasource.url=jdbc:postgresql://shuttle.proxy.rlwy.net:27489/railway?TimeZone=UTC
spring.datasource.username=postgres
spring.datasource.password=PyEqZFAqJwgLfcuIaVeQBDtQUcpWEWRX

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

openrouter.api.key=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
openrouter.model=openrouter/free