spring.application.name=matcher

spring.datasource.url=jdbc:postgresql://shuttle.proxy.rlwy.net:27489/railway?TimeZone=UTC
spring.datasource.username=postgres
spring.datasource.password=PyEqZFAqJwgLfcuIaVeQBDtQUcpWEWRX

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

gemini.api.key=AIzaSyArR7B1MrnjEg-lN5wBN_WOV0RWW0odgrA
