spring.application.name=matcher

spring.datasource.url=jdbc:postgresql://shuttle.proxy.rlwy.net:27489/railway?TimeZone=UTC
spring.datasource.username=postgres
spring.datasource.password=PyEqZFAqJwgLfcuIaVeQBDtQUcpWEWRX

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

openrouter.api.key=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
openrouter.model=nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free